# Generated by Django 5.2.14 on 2026-05-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='scientific_unit',
            new_name='department',
        ),
    ]
