# Generated by Django 5.2.14 on 2026-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sensor_set_id', models.PositiveSmallIntegerField()),
                ('sensor_type', models.CharField(choices=[('moisture_content', 'Moisture content'), ('out_temperature', 'Outdoor temperature'), ('in_temperature', 'Indoor temperature'), ('air_humidity', 'Air humidity'), ('light_intensity', 'Light intensity')], default='moisture_content', max_length=30)),
                ('unit', models.CharField(default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
