# Generated by Django 5.2.14 on 2026-05-26 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_number', models.PositiveIntegerField(default=1)),
                ('pot_number', models.PositiveIntegerField(default=1)),
                ('raw_value', models.IntegerField(blank=True, null=True)),
                ('moisture_percent', models.FloatField()),
                ('air_temperature', models.FloatField(blank=True, null=True)),
                ('air_humidity', models.FloatField(blank=True, null=True)),
                ('pressure_hpa', models.FloatField(blank=True, null=True)),
                ('soil_temperature', models.FloatField(blank=True, null=True)),
                ('light_lux', models.FloatField(blank=True, null=True)),
                ('pump_on', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='experiments.experiment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['experiment', 'created_at'], name='measurement_experim_9b5d9c_idx'), models.Index(fields=['station_number', 'pot_number', 'created_at'], name='measurement_station_224b14_idx'), models.Index(fields=['created_at'], name='measurement_created_d14a08_idx')],
            },
        ),
    ]
