

# Generated by Django 5.2.14 on 2026-05-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_alter_measurement_experiment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_experim_9b5d9c_idx',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='experiment',
        ),
    ]
