# Generated by Django 5.2.13 on 2026-05-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_remove_measurement_device_name_measurement_sensor'),
        ('measurements', '0003_station_pot_and_optional_raw'),
    ]

    operations = [
    ]
