# Generated by Django 5.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("experiments", "0003_experiment_sensor_frequencies"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CameraFrame",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="camera_frames/%Y/%m/%d/")),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("captured_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="captured_camera_frames", to=settings.AUTH_USER_MODEL)),
                ("experiment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="camera_frames", to="experiments.experiment")),
            ],
            options={"ordering": ["-captured_at"]},
        ),
    ]
