# Generated by Django 5.2.17 on 2026-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera_frames', '0002_cameradevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradevice',
            name='sensor_set_id',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
