# Generated by Django 5.2.17 on 2026-08-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpcommand',
            name='pot_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pumpcommand',
            name='station_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='pumpcommand',
            index=models.Index(fields=['station_number', 'pot_number', 'created_at'], name='pump_contro_station_525bf1_idx'),
        ),
    ]
