# Generated by Django 5.2.16 on 2026-08-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='notes/%Y/%m/%d/'),
        ),
    ]
