# Generated by Django 5.2.16 on 2026-09-09 18:10

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_images(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    NoteImage = apps.get_model('notes', 'NoteImage')
    for note in Note.objects.exclude(image='').exclude(image=None):
        NoteImage.objects.create(note=note, image=note.image.name)


def restore_legacy_images(apps, schema_editor):
    Note = apps.get_model('notes', 'Note')
    NoteImage = apps.get_model('notes', 'NoteImage')
    for image in NoteImage.objects.select_related('note').order_by('uploaded_at', 'id'):
        if not image.note.image:
            image.note.image = image.image.name
            image.note.save(update_fields=['image'])


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.note')),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
        migrations.RunPython(copy_legacy_images, restore_legacy_images),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
    ]
