name: Backend tests

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pobierz repozytorium
        uses: actions/checkout@v4

      - name: Uruchom testy backendu
        run: |
          cd backend
          docker compose up -d
          docker compose exec -T web python manage.py test